spring.application.name=ExpenseTracker

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5434/ExpenseUser
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
